INSERT INTO killrvideo.users(userid, firstname, lastname, email, created_date)
VALUES(${userId1}, 'fn1', 'ln1', 'email1@google.com', toTimestamp(now()));

INSERT INTO killrvideo.users(userid, firstname, lastname, email, created_date)
VALUES(${userId2}, 'fn2', 'ln2', 'email2@google.com', toTimestamp(now()));

INSERT INTO killrvideo.users(userid, firstname, lastname, email, created_date)
VALUES(${userId3}, 'fn3', 'ln3', 'email3@google.com', toTimestamp(now()));

INSERT INTO killrvideo.users(userid, firstname, lastname, email, created_date)
VALUES(${userId4}, 'fn4', 'ln4', 'email4@google.com', toTimestamp(now()));

INSERT INTO killrvideo.users(userid, firstname, lastname, email, created_date)
VALUES(${userId5}, 'fn5', 'ln5', 'email5@google.com', toTimestamp(now()));