UPDATE killrvideo.video_playback_stats SET views = views + ${view1}
WHERE videoid=${videoid1};

UPDATE killrvideo.video_playback_stats SET views = views + ${view2}
WHERE videoid=${videoid2};

UPDATE killrvideo.video_playback_stats SET views = views + ${view3}
WHERE videoid=${videoid3};

UPDATE killrvideo.video_playback_stats SET views = views + ${view4}
WHERE videoid=${videoid4};

UPDATE killrvideo.video_playback_stats SET views = views + ${view5}
WHERE videoid=${videoid5};